# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  node: circleci/node@4.6
  cypress: cypress-io/cypress@1.29.0
jobs:
  linter:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
  deploy:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn deploy
workflows:
  tests:
    jobs:
      - linter
      - cypress/run:
          requires:
            - linter
          config: 'baseUrl=http://localhost:5000'
          install-command: yarn install --frozen-lockfile
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:5000'
      - deploy:
          requires:
            - cypress/run