# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  node: circleci/node@4.6
jobs:
  linter:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn lint
workflows:
  test_my_app:
    jobs:
      - linter